Support DEX orders on stellar client
codescalers/tfgrid-sdk-dart pull request #119
Opened 2024-12-05 10:48 UTC by AlaaElattar

### Description

- support placing, canceling, and listing orders
### Changes

- Added `createOrders`, user can create buy/sell orders for specific assets.
- Added `cancelOrder`, user can cancel specific order with its id.
- Added `getOrderBook`, user can get oder book of the conversion between any 2 assets.
- Added `listMyOffers`, user can list its offers.
### Related Issues

#112 
### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Code format
- [ ] Screenshots/Video attached (needed for UI changes)

2024-12-25 07:52 UTC, zaelgohary reviewed
Please fix analyze workflow. Also, can you replace prints with logger?

2025-01-09 15:04 UTC, zaelgohary reviewed
I get insufficient balance although I have enough XLMs in my balance.

![image](https://github.com/user-attachments/assets/33e2fb20-acfd-4b91-8234-3b887c0282d8)

Also, USDC asset code is not added while adding trustline,


Logger is not working. I had to edit the logger value in client to the following for it to print.

```
  var logger = Logger(
    printer: PrettyPrinter(
      methodCount: 2,
      errorMethodCount: 8,
      lineLength: 120,
      colors: true,
      printEmojis: true,
    ),
    level: Level.debug,
    filter: ProductionFilter(),
  );
```

2025-01-09 15:04 UTC, zaelgohary commented on packages/stellar_client/lib/src/client.dart
> +
```suggestion
      if (offers.records.isEmpty) logger.i('No offers found for account: $accountId');
      
```

2025-01-09 15:04 UTC, zaelgohary commented on packages/stellar_client/lib/src/client.dart
> +      orElse: () => throw Exception('Insufficient balance in $sellingAsset'),
```suggestion
      orElse: () => throw Exception('Insufficient $sellingAsset balance.'),
```

2025-01-09 15:04 UTC, zaelgohary commented on packages/stellar_client/lib/src/client.dart
> +          'Insufficient balance in $sellingAsset. Available: $availableBalance');
```suggestion
          'Insufficient $sellingAsset balance. Available: $availableBalance');
```

2025-01-13 06:55 UTC, zaelgohary commented on packages/stellar_client/lib/src/client.dart
> +      required String offerId,
How can I get the offer ID? It isn't included in the order response or the order book.

2025-01-13 06:59 UTC, zaelgohary reviewed
Although I create an order successfully, I get an empty list when listing offers.

![image](https://github.com/user-attachments/assets/54e52763-1f4c-4724-a61a-e128427938d3)

2025-01-13 07:21 UTC, zaelgohary commented
I get the following error while updating the order.

![image](https://github.com/user-attachments/assets/c187f5f2-df24-4886-a9de-f914949739e3)

2025-01-14 10:38 UTC, AlaaElattar commented
> Although I create an order successfully, I get an empty list when listing offers.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/402451999-54e52763-1f4c-4724-a61a-e128427938d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NDU4MTUsIm5iZiI6MTczNjg0NTUxNSwicGF0aCI6Ii80MDc3MDUwMS80MDI0NTE5OTktNTRlNTI3NjMtMWY0Yy00NzI0LWE2MWEtZTEyODQyNzkzOGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDA5MDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZjQ4MmI4NzVlODUzNjk1Y2RjZGY1Y2MzNzhhODVjYjEzY2I4OTUyYjEwZDQ4Y2YwOTExMmEzMjc2MThmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3y75Z3yFWXbth_qAIfsGLoI52XVk58df-SG2m_fXBJs)

![Screenshot 2025-01-14 at 12 37 02 PM](https://github.com/user-attachments/assets/a9c08109-370a-46b2-bf20-4635534a5766)

2025-01-14 10:46 UTC, AlaaElattar commented
> I get the following error while updating the order.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/402456176-c187f5f2-df24-4886-a9de-f914949739e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NDU4MTQsIm5iZiI6MTczNjg0NTUxNCwicGF0aCI6Ii80MDc3MDUwMS80MDI0NTYxNzYtYzE4N2Y1ZjItZGYyNC00ODg2LWE5ZGUtZjkxNDk0OTczOWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDA5MDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZjE2NjQ4OTRlYTk0YzBiNGM3N2ZlMzE4NWFkN2RkNWZjN2JhNjk3M2UxNDVjYWE3MTc2YTFhYzhmOTZmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.skY2P7eAYogtIxzIzLnCTXoGUnqPauRjnUylEYS2N1I)

- The offers list is empty which means the order already done.
- That's why its not found when updating it in the offers.

2025-02-09 12:11 UTC, zaelgohary requested changes
- [x] Can we add Docs to the PR? Please, don't forget to handle the units we use in creating/updating orders.

![image](https://github.com/user-attachments/assets/bf759eb5-ef2c-4aae-ad07-e273fd5d2a68)


- [x] When creating order with price '.0001; I get the following err: (It leads the leading 0. Needs to be mentioned in the docs)

![image](https://github.com/user-attachments/assets/304beaea-834c-4635-9087-3150776da36b)

- [x] When creating account through threefold service on Testnet, it failed to add USDC asset.

![image](https://github.com/user-attachments/assets/56773aee-e37a-468c-9eae-6d41c3db52e2)

- [ ] Amount before and after create order does not match the price

![image](https://github.com/user-attachments/assets/14a4bb13-6ce0-4752-b008-b6342ea52dc6)

- I created 4 offers, none of them were listed in the orderbook
![image](https://github.com/user-attachments/assets/aaeda45f-4e21-4b0f-8944-0e2887f7778a)

2025-02-18 11:04 UTC, zaelgohary requested changes
- [ ] Orderbook is not being updated with my offers. It lists only 6 offers. (Maybe it's paginated? idk.).

- [ ] I think the getOrderBook docs equation is incorrect.
![image](https://github.com/user-attachments/assets/8b49a87a-dbb1-403e-83d1-86a7a34b1601)

2025-02-18 20:21 UTC, AlaaElattar commented
> * [ ]  Orderbook is not being updated with my offers. It lists only 6 offers. (Maybe it's paginated? idk.).
> * [ ]  I think the getOrderBook docs equation is incorrect.
>   ![image](https://private-user-images.githubusercontent.com/40770501/414221473-8b49a87a-dbb1-403e-83d1-86a7a34b1601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk5MDczMDMsIm5iZiI6MTczOTkwNzAwMywicGF0aCI6Ii80MDc3MDUwMS80MTQyMjE0NzMtOGI0OWE4N2EtZGJiMS00MDNlLTgzZDEtODZhN2EzNGIxNjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE4VDE5MzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZTdhNWI1MmNlODUxNTgwOGNlMzQ2MmQzNWJmNTllMjRkODQ2YTRhMmNhMmU3NDQ2NzA4YTdhZjQ1M2JjYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qy3FDpw9PqulW5K1ney7mrKZut4KdiwjZ1PioN_2zGs)

- I check the representation again and what i noticed about stellar representation is :
```bash
Total selling amount = Buy amount * price
price = 1 / price
```

2025-02-18 20:28 UTC, AlaaElattar commented
> * [ ]  Orderbook is not being updated with my offers. It lists only 6 offers. (Maybe it's paginated? idk.).
> * [x]  I think the getOrderBook docs equation is incorrect.
>   ![image](https://private-user-images.githubusercontent.com/40770501/414221473-8b49a87a-dbb1-403e-83d1-86a7a34b1601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk5MTAzODYsIm5iZiI6MTczOTkxMDA4NiwicGF0aCI6Ii80MDc3MDUwMS80MTQyMjE0NzMtOGI0OWE4N2EtZGJiMS00MDNlLTgzZDEtODZhN2EzNGIxNjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE4VDIwMjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNmU0Y2RkODBiNTdjY2E0NzQxOTliYmU2NGJhMGEwZjIwNDNkZTFkNTIzYTg1NzMxOWVkNmEwZjhhNDU1ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mQCTImEqdOBlbynhAGPp5niaWFH_EW-GWFJvFb8ZeJE)

- About the first point of order book, I found that it doesn't support traditional pagination.
- It returns a snapshot of the current order book state. (only limited number of bids and asks)

2025-02-19 04:44 UTC, zaelgohary approved these changes
Good job, @AlaaElattar!

2025-04-27 11:47 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
>    Future<bool> addTrustLine() async {
This method adds more than one trustline and doesn't take args to add the trustline. So I think you should call it `addConfiguredTrustlines`

2025-04-27 11:47 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +      );
You also need to check if the balances have the buying asset

2025-04-27 11:47 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +  Future<bool> cancelOrder(
I expect the cancelOrder to take only the order ID.

2025-04-27 11:47 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +      required String buyingAssetCode,
The order already has the buying and selling assets.

2025-04-27 11:47 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +  Future<List<TradeResponse>> getTradingHistory(String accountId) async {
Don't we already have the account ID within the client instance?

2025-04-27 13:17 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +  Future<List<TradeResponse>> getTradingHistory(String accountId) async {
or move it out the client to be a helper as it doesn't require having a wallet secret

2025-04-27 13:17 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +  Future<Stream<OrderBookResponse>> getOrderBook(
The orderbook doesn't require being on the client. Can you make it as a helper to use it without a secret?

2025-04-30 12:21 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +      }
We did 2 loops on balances to check if the account has the buying and selling assets, however, this could be done in one loop

2025-04-30 12:21 UTC, AhmedHanafy725 commented on packages/stellar_client/lib/src/client.dart
> +  Future<bool> cancelOrder({required String offerId, String? memo}) async {
Why is the memo needed to cancel the order?

2025-05-04 09:18 UTC, AhmedHanafy725 approved these changes

2025-05-04 12:11 UTC, merged