Add Signer pkg
codescalers/tfgrid-sdk-dart pull request #7
Opened 2023-11-22 16:09 UTC by AlaaElattar

- add signer pkg to sign and verify data by using mnemonic or seed.

2024-06-26 09:53 UTC, AhmedHanafy725 requested changes

2024-06-26 09:53 UTC, AhmedHanafy725 commented on packages/signer/lib/src/sign.dart
> +  KPType? _type;
`_type` is set later but never used, do we need it?

2024-06-26 10:13 UTC, AlaaElattar commented on Makefile
I thought it can be used to run tests and check coverage

2024-06-26 10:16 UTC, AlaaElattar commented on packages/signer/bin/signer.dart
not a test file, the file contains main function helps me to test the pkg manually.

2024-06-26 10:50 UTC, AhmedHanafy725 commented on packages/signer/bin/signer.dart
okay then maybe rename the directory to examples or scripts

2024-06-27 06:21 UTC, AlaaElattar commented on packages/signer/lib/src/types.dart
> +    }
I can replace with function like that 
```dart
String kpTypeToString(KPType type) {
  switch (type) {
    case KPType.sr25519:
      return 'sr25519';
    case KPType.ed25519:
      return 'ed25519';
    default:
      return '';
  }
}
```
what do u think ?

2024-06-27 11:34 UTC, AhmedHanafy725 approved these changes

2024-06-27 11:35 UTC, merged