Add Workflows
codescalers/tfgrid-sdk-dart pull request #8
Opened 2023-11-26 10:39 UTC by AlaaElattar

2023-11-27 08:37 UTC, AlaaElattar commented
- According to the unknown value in the codecov badge will be updated after merging with main.

2024-06-26 12:22 UTC, AhmedHanafy725 reviewed
please resolve the conflicts here

2024-06-26 13:12 UTC, AhmedHanafy725 commented
do we need to keep the coverage directory uploaded?

2024-06-27 13:42 UTC, AhmedHanafy725 requested changes

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/build.yaml
> +  pull_request:
please add on push on the main branch too.

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/build.yaml
the file name is called `build` while it doesn't build the code. maybe call it `analyze`

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/build.yaml
> +      - name: Linting
```suggestion
      - name: Analyze
```

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/coverage.yaml
> +      - main
same here add on pushing on the main branch.

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/coverage.yaml
> +          melos exec --dir-exists="coverage" -- bash -c 'dart pub global run coverde filter --input coverage/lcov.info --output coverage/filtered.lcov.info --filters .g.dart'
please split running the tests and calculating the coverage into 2 different steps. the coverage step should check if the tests passed successfully to run.

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/coverage.yaml
> +        uses: codecov/codecov-action@v3
this step should check if the coverage step is finished without errors

2024-06-27 13:42 UTC, AhmedHanafy725 commented on .github/workflows/tests.yaml
this workflow is a duplicate of the coverage workflow. let's remove it

2024-06-27 14:13 UTC, AhmedHanafy725 approved these changes

2024-06-27 14:14 UTC, merged